CREATE TABLE `completed_checklists` (
	`id` int AUTO_INCREMENT NOT NULL,
	`checklistCode` varchar(50) NOT NULL,
	`checklistName` text NOT NULL,
	`categoria` varchar(50) NOT NULL,
	`modelo` varchar(100) NOT NULL,
	`resultado` enum('OK','NAO_OK','NAO_APLICAVEL') NOT NULL,
	`executanteName` varchar(255) NOT NULL,
	`executanteMatricula` varchar(50) NOT NULL,
	`liderName` varchar(255),
	`liderMatricula` varchar(50),
	`inspectorName` varchar(255),
	`inspectorMatricula` varchar(50),
	`dataFabricacao` varchar(50),
	`dataRecuperacao` varchar(50) NOT NULL,
	`numeroOP` varchar(50),
	`numeroSerie` varchar(50),
	`totalEtapas` int NOT NULL,
	`etapasOK` int NOT NULL DEFAULT 0,
	`etapasNaoOK` int NOT NULL DEFAULT 0,
	`etapasNaoAplicavel` int NOT NULL DEFAULT 0,
	`pdfFileName` varchar(255),
	`email` varchar(320),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `completed_checklists_id` PRIMARY KEY(`id`)
);
