/**
 * Configurações de todos os 8 checklists disponíveis
 * Dados extraídos dos PDFs oficiais da MRS
 */

export type ChecklistType = 
  | "CL-ENG-1029" // Inspeção da Lateral do Truque BARBER
  | "CL-ENG-1030" // Inspeção da Lateral do Truque Swing Motion
  | "CL-ENG-1031" // Inspeção da Lateral do Truque Ride Control
  | "CL-ENG-1032" // Inspeção da Lateral do Truque Ride Master, Motion Control, Hibrido
  | "CL-ENG-1033" // Inspeção da Travessa do Truque Ride Master, Motion Control
  | "CL-ENG-1034" // Inspeção da Travessa do Truque Barber
  | "CL-ENG-1035" // Inspeção da Travessa do Truque Ride Control
  | "CL-ENG-1036" // Inspeção da Travessa do Truque Swing Motion
  | "CL-ENG-1066"; // Inspeção e Recuperação de Triângulo de Freio

export interface EtapaConfig {
  numero: number;
  sistema: string;
  subsistema: string;
  atividade: string;
  resultadoEsperado: string;
  medidas: { label: string; unidade: string }[];
}

export interface ChecklistConfig {
  codigo: ChecklistType;
  versao: string;
  titulo: string;
  categoria: "Lateral" | "Travessa" | "Triângulo";
  tipoTruque: string;
  modelos: string[];
  dataEmissao: string; // ex: 25/06/2024
  validadeAte: string;
  procedimentoOrigem: string;
  etapas: EtapaConfig[];
}

export const CHECKLISTS_CONFIG: Record<ChecklistType, ChecklistConfig> = {
  "CL-ENG-1029": {
    codigo: "CL-ENG-1029",
    versao: "04.01",
    titulo: "Inspeção da Lateral do Truque BARBER",
    categoria: "Lateral",
    tipoTruque: "BARBER",
    modelos: ["Lateral BARBER 6.1/2x12", "Lateral BARBER 6x11", "Lateral BARBER 5.1/2x10", "Lateral BARBER 7x12 S2F", "Lateral BARBER 6.1/2x9 S2F"],
    dataEmissao: "25/06/2024",
    validadeAte: "25/06/2029",
    procedimentoOrigem: "POP-ENG-1088",
    etapas: [
      {
        numero: 1,
        sistema: "Laterais",
        subsistema: "Orelhas do Pedestal Estreito S2F",
        atividade: "Inspecionar visualmente a distância entre orelhas do pedestal com o calibre MV-51-9906-245-00 [7\"x12\"] e MV-51-9906-215-00 [6.1/2\"x9\"].",
        resultadoEsperado: "Lado \"passa\" do calibre deve passar e o lado \"não passa\" não deve passar entre as orelhas do pedestal. Dimensões dentro dos valores especificados",
        medidas: [],
      },
      {
        numero: 2,
        sistema: "Laterais",
        subsistema: "Espessura das Orelhas S2F",
        atividade: "Inspecionar visualmente a espessura das orelhas do pedestal com o calibre MV-51-9906-062-00 [6.1/2\"x9\"] e MV-51-9906-156-00 [7\"x12\"].",
        resultadoEsperado: "Lado \"passa\" do calibre deve passar e o lado \"não passa\" não deve passar entre as orelhas do pedestal. Dimensões dentro dos valores especificados",
        medidas: [],
      },
      {
        numero: 3,
        sistema: "Laterais",
        subsistema: "Folga na Região do Pedestal",
        atividade: "Verificar manualmente com uso de esquadro a perpendicularidade entre topo do pedestal e pernas.",
        resultadoEsperado: "Folga na região de trabalho do adaptador de cada perna: máxima = 2,0 mm, mínima = 0 mm. Limitado a região de funcional.",
        medidas: [
          { label: "D1", unidade: "mm" },
          { label: "D2", unidade: "mm" },
          { label: "E1", unidade: "mm" },
          { label: "E2", unidade: "mm" },
        ],
      },
      {
        numero: 4,
        sistema: "Laterais",
        subsistema: "Abertura das Pernas",
        atividade: "Verificar manualmente com uso de calibres a abertura entre pernas do pedestal. Calibre MV-51-9906-180 [5.1/2\"x10\"]; MV-51-9906-051 [6.1/2\"x12\"]; MV-51-9906-052 [6\"x11\"]",
        resultadoEsperado: "Os calibres não devem passar na região funcional do pedestal onde atua o adaptador.",
        medidas: [],
      },
      {
        numero: 5,
        sistema: "Laterais",
        subsistema: "Abertura das Pernas",
        atividade: "Verificar manualmente com uso de calibres a abertura entre pernas do pedestal. Calibre MV-51-9906-181[5.1/2\"x10\"]; MV-51-9906-053 [6.1/2\"x12\"]; MV-51-9906-054 [6\"x11\"].",
        resultadoEsperado: "Os calibres devem passar em toda a extensão entre as pernas.",
        medidas: [],
      },
      {
        numero: 6,
        sistema: "Laterais",
        subsistema: "Largura Pedestal",
        atividade: "Verificar manualmente com uso de calibres a largura do pedestal. Calibre MV-51-9906-056 [6\"x11\" e 6.1/2\"x12\"]; MV-51-9906-179 [5.1/2\"x10\"].",
        resultadoEsperado: "Os Calibre devem passar no lado passa e não passar no lado não passa, na região funcional do adaptador.",
        medidas: [],
      },
      {
        numero: 7,
        sistema: "Laterais",
        subsistema: "Angularidade dos Pedestais",
        atividade: "Verificar a angularidade entre pedestais e a base de molas. Assentar o dispositivo de nivelamento da base de molas desenho MV-51-9906-221-00 na parte central do assento das molas. Com a utilização do goniômetro (angle star), faz-se a leitura zerando o aparelho.",
        resultadoEsperado: "Desnivelamento entre base de molas e pedestal igual ou inferior a 1,6°.",
        medidas: [
          { label: "Ângulo", unidade: "°" },
          { label: "Ângulo", unidade: "°" },
        ],
      },
      {
        numero: 8,
        sistema: "Laterais",
        subsistema: "Angularidade dos Pedestais",
        atividade: "Verificar a angularidade entre pedestais. Colocar o goniômetro (angle star), no teto de um dos pedestais do truque, zerando o instrumento. Transferir o aparelho goniômetro (angle star) para o teto do outro pedestal e verificar o desnível.",
        resultadoEsperado: "Desnível entre pedestais igual ou inferior a 1º. Desnível entre pedestais usinados igual ou inferior a 0,2º.",
        medidas: [{ label: "Ângulo", unidade: "°" }],
      },
      {
        numero: 9,
        sistema: "Laterais",
        subsistema: "Teto dos Pedestais",
        atividade: "Garantir a recuperação do teto do pedestal de forma a não comprometer a sua planicidade, utilizar calibre MV-51-9906-063-00 no sentido longitudinal e trans-versal.",
        resultadoEsperado: "Lateral com concavidade inferior a 1,0 mm e convexidade até 1,0 mm. Para pedestal estreito medir 20 mm a partir da extremidade do pedestal para dentro.",
        medidas: [
          { label: "CONVEXIDADE", unidade: "mm" },
          { label: "CONVEXIDADE", unidade: "mm" },
          { label: "CONCAVIDADE", unidade: "mm" },
          { label: "CONCAVIDADE", unidade: "mm" },
        ],
      },
      {
        numero: 10,
        sistema: "Laterais",
        subsistema: "Chapas dos pedestais",
        atividade: "Para os truques que não possuem PAD ou Penssy Pad, e que possuem chapas de desgastes do pedestal as mesmas deverão ser aplicadas de acordo com o esquema da tabela Tipo de Truque.",
        resultadoEsperado: "Chapas das do pedestal, soldadas, livre de trincas ou quebras.",
        medidas: [],
      },
      {
        numero: 11,
        sistema: "Laterais",
        subsistema: "Chapas das colunas",
        atividade: "Inspecionar visualmente as chapas das colunas quanto à presença, quanto a trincas ou quebras.",
        resultadoEsperado: "Chapas das colunas presentes, livre de trincas ou quebras.",
        medidas: [],
      },
      {
        numero: 12,
        sistema: "Laterais",
        subsistema: "Chapas das colunas",
        atividade: "Verificar manualmente com o calibre específico do tipo de truque a Distância entre chapas de desgaste das colunas. Calibre MV-51-9906-035 [6\" x 11\" e 6.1/2\" x 12\"]; MV-51-9906-210 [5.1/2\" x 10\"]; MV-51-9906-222 [S2F 7\"x12\"]; MV-51-9906-239 [S2F 6.1/2\"x9\"]",
        resultadoEsperado: "Folga máxima de 4 mm.",
        medidas: [
          { label: "Folga", unidade: "mm" },
          { label: "Folga", unidade: "mm" },
        ],
      },
      {
        numero: 13,
        sistema: "Laterais",
        subsistema: "Chapas das colunas",
        atividade: "Verificar manualmente com o calibre específico do tipo de truque a Largura da coluna de desgaste das colunas. Calibre MV-51-9906-035 [6\" x 11\" e 6.1/2\" x 12\"]; MV-51-9906-210 [5.1/2\" x 10\"]; MV-51-9906-222 [S2F 7\"x12\"]; MV-51-9906-239 [S2F 6.1/2\"x9\"]",
        resultadoEsperado: "Folga máxima de 3 mm e 5 mm para S2F;",
        medidas: [
          { label: "Folga", unidade: "mm" },
          { label: "Folga", unidade: "mm" },
        ],
      },
      {
        numero: 14,
        sistema: "Laterais",
        subsistema: "Verificação da Base Rígida",
        atividade: "Inspecionar manualmente se a quantidade de botões de paridade (mamicas) indicada na lateral está compatível com a realidade utilizando o calibre MV-51-9906-043-00",
        resultadoEsperado: "Quantidade de botões na lateral compatível com valor medido.",
        medidas: [{ label: "Quantidade", unidade: "" }],
      },
      {
        numero: 15,
        sistema: "Laterais",
        subsistema: "Verificação do Dimensional das Guias do Triângulo de Freio",
        atividade: "Inspecionar visualmente as chapas da corrediça quanto à sua presença, quanto a trincas, quebras, partes faltantes e sua fixação por solda. Inspecionar manualmente o dimensional da corrediça utilizando o calibre MV-51-9906-012-00",
        resultadoEsperado: "Chapa de desgaste da corrediça presente, livre de trincas, quebras e partes faltantes. Chapa de desgaste da corrediça fixada com cordão de solda na parte superior. Calibre lado \"passa\" deve ser introduzido por completo e passar em toda extensão da corrediça, o lado \"não passa\" não deve passar por toda extensão da corrediça e não deve haver contato entre a aba da corrediça e o calibre.",
        medidas: [],
      },
    ],
  },

  "CL-ENG-1030": {
    codigo: "CL-ENG-1030",
    versao: "03.01",
    titulo: "Inspeção da Lateral do Truque Swing Motion",
    categoria: "Lateral",
    tipoTruque: "Swing Motion",
    modelos: ["Lateral Swing Motion 6.1/2x9", "Lateral Swing Motion 7x12"],
    dataEmissao: "25/06/2024",
    validadeAte: "25/06/2029",
    procedimentoOrigem: "POP-ENG-1092",
    etapas: [
      {
        numero: 1,
        sistema: "Laterais",
        subsistema: "Distância entre Orelhas do Pedestal",
        atividade: "Inspecionar visualmente a distância entre orelhas do pedestal utilizando o calibre apropriado para a dimensão da manga do truque. Calibre MV-51-9906-215-00 [6.1/2\"x9\"] e MV-51-9906-217-00 [7\"x12\"]",
        resultadoEsperado: "Lado \"passa\" do calibre deve passar e o lado \"não passa\" não deve passar entre as orelhas do pedestal (em toda a extensão).",
        medidas: [],
      },
      {
        numero: 2,
        sistema: "Laterais",
        subsistema: "Espessura Orelhas do Pedestal",
        atividade: "Inspecionar visualmente a espessura das orelhas do pedestal utilizando o calibre apropriado para a dimensão da manga do truque. Utilizar calibre MV-51-9906-216-00 [6.1/2\"x9\"] e MV-51-9906-218-00 [7\"x12\"]",
        resultadoEsperado: "Lado \"passa\" do calibre deve passar e o lado \"não passa\" não deve passar entre as orelhas do pedestal (em toda a extensão).",
        medidas: [],
      },
      {
        numero: 3,
        sistema: "Laterais",
        subsistema: "Distância entre chapas",
        atividade: "Inspecionar visualmente as chapas da coluna quanto à presença, trincas, quebras, partes faltantes, fixação por parafuso ou solda. Verificar manualmente com auxilio de calibres MV-51-9906-113-00 [6.1/2\"x9\"] e MV-51-9906-153-00 [7\"x 12\"].",
        resultadoEsperado: "Chapas de desgaste presente, livre de trincas, quebras e partes faltantes, chapas fixadas por parafuso e porca auto travante ou fixadas por solda. O lado \"passa\" do calibre deve passar na chapa de desgaste, o lado \"não passa\" não deve passar na chapa (verificação deve ser realizada em toda extensão da chapa de desgaste).",
        medidas: [],
      },
      {
        numero: 4,
        sistema: "Laterais",
        subsistema: "Verificação da Base Rígida",
        atividade: "Inspecionar manualmente se a quantidade de botões de paridade (mamicas) indicada na lateral está compatível com a realidade utilizando o calibre MV-51-9906-043-00",
        resultadoEsperado: "Quantidade de botões na lateral compatível com valor medido.",
        medidas: [{ label: "Quantidade", unidade: "" }],
      },
      {
        numero: 5,
        sistema: "Laterais",
        subsistema: "Inspeção do ROCKER SEAT",
        atividade: "Inspecionar visualamente o Rocker Seat do teto do pedestal. Caso necessário substituir utilizando chapa de retenção.",
        resultadoEsperado: "Rocker Seat presente e com chapa de retenção.",
        medidas: [],
      },
      {
        numero: 6,
        sistema: "Laterais",
        subsistema: "Verificação do Dimensional das Guias do Triângulo de Freio",
        atividade: "Inspecionar visualmente as chapas da corrediça quanto à sua presença, quanto a trincas, quebras, partes faltantes e sua fixação por solda. Inspecionar manualmente o dimensional da corrediça utilizando o calibre MV-51-9906-012-00.",
        resultadoEsperado: "Chapa de desgaste da corrediça presente, livre de trincas, quebras e partes faltantes. Chapa de desgaste da corrediça fixada com cordão de solda na parte superior. Calibre lado \"passa\" deve ser introduzido por completo e passar em toda a extensão da corrediça, o lado \"não passa\" não deve passar por toda extensão da corrediça e não deve haver contato entre a aba da corrediça e o calibre.",
        medidas: [],
      },
    ],
  },

  "CL-ENG-1031": {
    codigo: "CL-ENG-1031",
    versao: "03.01",
    titulo: "Inspeção da Lateral do Truque Ride Control",
    categoria: "Lateral",
    tipoTruque: "Ride Control",
    modelos: ["Ride Control 5.1/2x10", "Ride control 6.1/2x9", "Ride Control 6x11", "Ride Control 6.1/2x12", "Ride control 6.1/2x9 Usinado", "Ride control 7x12 Usinado"],
    dataEmissao: "25/06/2024",
    validadeAte: "25/06/2029",
    procedimentoOrigem: "POP-ENG-1090",
    etapas: [
      {
        numero: 1,
        sistema: "Laterais",
        subsistema: "Distância entre Orelhas do Pedestal Estreito",
        atividade: "Inspecionar visualmente a distância entre orelhas do pedestal com o calibre especifico. Calibre MV-51-9906-214 [6.1/2\"x9\"]; MV-51-9906-200 [6.1/2\"x9\" usinado]; MV51-9906-199 [7\"x12\" usinado].",
        resultadoEsperado: "Lado \"passa\" do calibre deve passar e o lado \"não passa\" não deve passar entre as orelhas do pedestal.",
        medidas: [],
      },
      {
        numero: 2,
        sistema: "Laterais",
        subsistema: "Espessura das Orelhas do Pedestal",
        atividade: "Inspecionar visualmente a espessuradas orelhas do pedestal com o calibre especifico. Calibre MV-51-9906-062 [6.1/2\"x9\"]; MV-51-9906-193 [6.1/2\"x9\" usinado]; MV51-9906-192 [7\"x12\" usinado].",
        resultadoEsperado: "Lado \"passa\" do calibre deve passar e o lado \"não passa\" não deve passar entre as orelhas do pedestal. Dimensões dentro dos valores especificados",
        medidas: [],
      },
      {
        numero: 3,
        sistema: "Laterais",
        subsistema: "Folga na região funcional do adaptador",
        atividade: "Verificar manualmente com uso de esquadro a perpendicularidade entre topo do pedestal e pernas.",
        resultadoEsperado: "Folga na região de trabalho do adaptador de cada perna: máxima = 2,0 mm, mínima = 0 mm. Limitado a região de funcional.",
        medidas: [
          { label: "D1", unidade: "mm" },
          { label: "D2", unidade: "mm" },
          { label: "E1", unidade: "mm" },
          { label: "E2", unidade: "mm" },
        ],
      },
      {
        numero: 4,
        sistema: "Laterais",
        subsistema: "Abertura das pernas do pedestal",
        atividade: "Verificar manualmente com uso de calibres a abertura entre pernas do pedestal. Calibre MV-51-9906-051 [6.1/2\"x12\"]; MV-51-9906-180 [5.1/2\"x10\"]; MV-51-9906-052 [6\"x11\"].",
        resultadoEsperado: "Os calibres não devem passar na região funcional do pedestal onde atua o adaptador.",
        medidas: [],
      },
      {
        numero: 5,
        sistema: "Laterais",
        subsistema: "Abertura das pernas do pedestal",
        atividade: "Verificar manualmente com uso de calibres a abertura entre pernas do pedestal. Calibre MV-51-9906-181 [5.1/2\"x10\"]; MV-51-9906-053 [6.1/2\"x12\"]; MV-51-9906-054 [6\"x11\"].",
        resultadoEsperado: "Os calibres devem passar em toda a extensão entre as pernas.",
        medidas: [],
      },
      {
        numero: 6,
        sistema: "Laterais",
        subsistema: "Largura Pedestal",
        atividade: "Verificar manualmente com uso de calibres a largura do pedestal. Calibre MV-51-9906-056 [6\"x11\" e 6.1/2\"x12\"]; MV-51-9906-179 [5.1/2\"x10\"].",
        resultadoEsperado: "Os Calibre devem passar no lado passa e não passar no lado não passa, na região funcional do adaptador.",
        medidas: [],
      },
      {
        numero: 7,
        sistema: "Laterais",
        subsistema: "Angularidade dos Pedestais",
        atividade: "Verificar a angularidade entre pedestais e a base de molas. Assentar o dispositivo de nivelamento da base de molas desenho MV-51-9906-221-00 na parte central do assento das molas. Com a utilização do goniômetro (angle star), faz-se a leitura zerando o aparelho.",
        resultadoEsperado: "Desnivelamento entre base de molas e pedestal igual ou inferior a 1,6°.",
        medidas: [
          { label: "Ângulo", unidade: "°" },
          { label: "Ângulo", unidade: "°" },
        ],
      },
      {
        numero: 8,
        sistema: "Laterais",
        subsistema: "Angularidade dos Pedestais",
        atividade: "Verificar a angularidade entre pedestais. Colocar o goniômetro (angle star), no teto de um dos pedestais do truque, zerando o instrumento. Transferir o aparelho goniômetro (angle star) para o teto do outro pedestal e verificar o desnível.",
        resultadoEsperado: "Desnível entre pedestais igual ou inferior a 1º. Desnível entre pedestais usinados igual ou inferior a 0,2º.",
        medidas: [{ label: "Ângulo", unidade: "°" }],
      },
      {
        numero: 9,
        sistema: "Laterais",
        subsistema: "Teto dos Pedestais",
        atividade: "Garantir a recuperação do teto do pedestal de forma a não comprometer a sua planicidade, utilizar calibre MV-51-9906-063-00 no sentido longitudinal e trans-versal.",
        resultadoEsperado: "Lateral com concavidade inferior a 1,0 mm e convexidade até 1,0 mm. Para pedestal estreito medir 20 mm a partir da extremidade do pedestal para dentro.",
        medidas: [
          { label: "CONVEXIDADE", unidade: "mm" },
          { label: "CONVEXIDADE", unidade: "mm" },
          { label: "CONCAVIDADE", unidade: "mm" },
          { label: "CONCAVIDADE", unidade: "mm" },
        ],
      },
      {
        numero: 10,
        sistema: "Laterais",
        subsistema: "Chapas dos pedestais",
        atividade: "Para os truques que não possuem PAD ou Penssy Pad, e que possuem chapas de desgastes do pedestal as mesmas deverão ser aplicadas de acordo com o esquema da tabela Tipo de Truque.",
        resultadoEsperado: "Chapas das do pedestal, soldadas, livre de trincas ou quebras.",
        medidas: [],
      },
      {
        numero: 11,
        sistema: "Laterais",
        subsistema: "Chapas das colunas",
        atividade: "Verificar manualmente com o calibre específico do tipo Passa, a Distância entre chapas de desgaste das colunas e a largura da coluna. Calibre MV-51-9906-032 [61/2\" x 9\" e 6.1/2\" x 12\"];MV-51-9906-031 [6\"x11\"]; MV-51-9906-126 [5.1l2\" x 10\"]; MV-51-9906-190 [7\"x12\" usinado]; MV-51-9906-191 [6.1/2\"x9\" usinado]",
        resultadoEsperado: "O calibre deve passar em toda a extensão das chapas e das colunas. A folga na largura da coluna deve ser de 3,0 a 8,0 mm para os modelos (6\"x11\"; 6.1/2\"X9\"; 6.1/2\"X12\"). Menor que 4,0 mm para (5.1/2\"x10\"). Menor que 2,0 mm para truques usinados (6.1/2\"x9 e 7\"x12\").",
        medidas: [],
      },
      {
        numero: 12,
        sistema: "Laterais",
        subsistema: "Chapas das colunas",
        atividade: "Verificar manualmente com o calibre especifico do tipo Nao Passa, a Distancia entre chapas de desgaste das colunas. Calibre MV-51-9906-034 [61/2\" x 9\" e 6.1/2\" x 12\"];MV-51-9906-033 [6\"x11\"]; MV-51-9906-125 [5.1l2\" x 10\"]; MV-51-9906-188 [7\"x12\" usinado]; MV-51-9906-189 [6.1/2\"x9\" usinado]",
        resultadoEsperado: "O calibre não deve passar em ambos os lados , em toda a extensão das chapas.",
        medidas: [],
      },
      {
        numero: 13,
        sistema: "Laterais",
        subsistema: "Guias anti-rotação",
        atividade: "Inspecionar manualmente as áreas de contato das guias anti-rotação com calibre específico. Calibre MV-51-9906-131 [5.1/2\"x10\"]; MV-51-9906-007 [6\"x11\"]; MV-51-9906-040 [6.1/2\"x12\" e 6.1/2\"x9\"]; MV-51-9906-195 [6.1/2\"x9\" usinado]; MV-51-9906-194 [7\"x12\" usinado]",
        resultadoEsperado: "Para truques usinados deslocar o calibre para um dos lados dividir o valor encontrado por 2 o resultado deve ser menor ou igual a 1,0 mm. Para truques comum deslocar o calibre para um dos lados dividir o valor encontrado por 2 o resultado deve ser menor ou igual 2,0 mm.",
        medidas: [
          { label: "Medida 1", unidade: "mm" },
          { label: "Medida 2", unidade: "mm" },
        ],
      },
      {
        numero: 14,
        sistema: "Laterais",
        subsistema: "Verificação da Base Rígida",
        atividade: "Inspecionar manualmente se a quantidade de botões de paridade (mamicas) indicada na lateral está compatível com a realidade utilizando o calibre MV-51-9906-043-00; MV-51-9906-016-00.",
        resultadoEsperado: "Quantidade de botões na lateral compatível com valor medido.",
        medidas: [{ label: "Quantidade", unidade: "" }],
      },
      {
        numero: 15,
        sistema: "Laterais",
        subsistema: "Verificação do Dimensional das Guias do Triângulo de Freio",
        atividade: "Inspecionar visualmente as chapas da corrediça quanto à sua presença, quanto a trincas, quebras, partes faltantes e sua fixação por solda. Inspecionar manualmente o dimensional da corrediça utilizando o calibre MV-51-9906-012-00.",
        resultadoEsperado: "Chapa de desgaste da corrediça presente, livre de trincas, quebras e partes faltantes. Chapa de desgaste da corrediça fixada com cordão de solda na parte superior. Calibre lado \"passa\" deve ser introduzido por completo e passar em toda a extensão da corrediça, o lado \"não passa\" não deve passar por toda extensão da corrediça e não deve haver contato entre a aba da corrediça e o calibre.",
        medidas: [],
      },
    ],
  },

  "CL-ENG-1032": {
    codigo: "CL-ENG-1032",
    versao: "02.01",
    titulo: "Inspeção da Lateral do Truque Ride Master, Motion Control, Híbrido",
    categoria: "Lateral",
    tipoTruque: "Ride Master, Motion Control, Híbrido",
    modelos: ["RIDE MASTER 6.1/2x9", "MOTION CONTROL 7x12", "MOTION CONTROL 6.1/2x9", "HÍBRIDO MC-RM 6.1/2x9"],
    dataEmissao: "25/06/2024",
    validadeAte: "25/06/2029",
    procedimentoOrigem: "POP-ENG-1091",
    etapas: [
      {
        numero: 1,
        sistema: "Laterais",
        subsistema: "Distância entre Orelhas do Pedestal",
        atividade: "Inspecionar visualmente a distância entre orelhas do pedestal utilizando o calibre apropriado para a dimensão da manga do truque. Truque 6.1l2\" x 9\": Calibre MV-51-9906-214-00 [RM] e MV-51-9906-257-00 [MC]. Para truques 7\"x12\" verificar a dimensão da cota C: 221,2 a 222,8 mm.",
        resultadoEsperado: "Lado \"passa\" do calibre deve passar e o lado \"não passa\" não deve passar entre as orelhas do pedestal.",
        medidas: [],
      },
      {
        numero: 2,
        sistema: "Laterais",
        subsistema: "Espessura Orelhas do Pedestal",
        atividade: "Inspecionar visualmente a espessura das orelhas do pedestal utilizando o calibre apropriado para a dimensão da manga do truque. [RM] 6.1/12x9 MV-51-9906-062-00; [MC] 6.1/2x9 MV-51-9906-258-00 e [MC] 7 x 12 MV-51-9906-156-00.",
        resultadoEsperado: "Lado \"passa\" do calibre deve passar e o lado \"não passa\" não deve passar entre as orelhas do pedestal (em toda a extensão).",
        medidas: [],
      },
      {
        numero: 3,
        sistema: "Laterais",
        subsistema: "Raio do Pedestal",
        atividade: "Inspecionar visualmente o raio do pedestal das laterais Ride Master observando sinais de contato com o adaptador.",
        resultadoEsperado: "Pedestais isentos de sinais de contato com o adaptador na região do raio.",
        medidas: [],
      },
      {
        numero: 4,
        sistema: "Laterais",
        subsistema: "Angularidade dos Pedestais",
        atividade: "Verificar a angularidade entre os pedestrais e a base de molas com o calibre MV-51-9906-221-00 e utilização do goniômetro.",
        resultadoEsperado: "Desnível entre base de molas e pedestal igual ou inferior a 1,6°.",
        medidas: [
          { label: "Ângulo", unidade: "°" },
          { label: "Ângulo", unidade: "°" },
        ],
      },
      {
        numero: 5,
        sistema: "Laterais",
        subsistema: "Angularidade dos Pedestais",
        atividade: "Verificar a angularidade entre pedestais. Colocar o goniômetro (angle star) no teto de um dos pedestais do truque, zerando o instrumento. Transferir o aparelho goniômetro (angle star) para o teto do outro pedestal e verificar o desnível.",
        resultadoEsperado: "Desnível entre pedestais igual ou inferior a 1°. Desnível entre pedestais usinados igual ou inferior a 0,2°.",
        medidas: [{ label: "Ângulo", unidade: "°" }],
      },
      {
        numero: 6,
        sistema: "Laterais",
        subsistema: "Teto dos Pedestais",
        atividade: "Garantir a recuperação do teto do pedestal de forma a não comprometer a sua planicidade, utili-zar calibre MV-51-9906-063-00 no sentido longi-tudinal e transversal.",
        resultadoEsperado: "Lateral com concavidade inferior a 1,0 mm e convexidade até1,0 mm. Para pedestal estreito medir 20 mm a partir da extremidade do pedestal para dentro.",
        medidas: [
          { label: "CONVEXIDADE", unidade: "mm" },
          { label: "CONVEXIDADE", unidade: "mm" },
          { label: "CONCAVIDADE", unidade: "mm" },
          { label: "CONCAVIDADE", unidade: "mm" },
        ],
      },
      {
        numero: 7,
        sistema: "Laterais",
        subsistema: "Distância entre chapas",
        atividade: "Verificar manualmente a distância entre as chapas das colunas laterais com a aplicação dos calibres passa [RM] MV-51-9906-058-00; [MC] MV-51-9906-255-00",
        resultadoEsperado: "O calibre deve passar por toda a estensão das chapas",
        medidas: [],
      },
      {
        numero: 8,
        sistema: "Laterais",
        subsistema: "Distância entre chapas",
        atividade: "Verificar manualmente a distância entre as chapas das colunas laterais com a aplicação do calibre não passa [RM] MV-51-9906-059-00; [MC] MV-51-9906-254-00",
        resultadoEsperado: "O calibre não deve passar em ambos os lados em toda extensão da chapa.",
        medidas: [],
      },
      {
        numero: 9,
        sistema: "Laterais",
        subsistema: "Largura da Coluna",
        atividade: "Verificar a largura da coluna da lateral com o calibre [RM] MV-51-9906-057-00; [MC] MV-51-9906-253-00. Para a lateral híbrida [MC-RM] Utilizar o calibre MV-51-9906-253-00",
        resultadoEsperado: "Uma lâmina de 3 mm não deve passar em um dos lados para tuques RM e MC. Para lateral hibrida MC-RM uma lâmina de 4 mm não deve passar em um dos lados.",
        medidas: [
          { label: "Medida 1", unidade: "mm" },
          { label: "Medida 2", unidade: "mm" },
        ],
      },
      {
        numero: 10,
        sistema: "Laterais",
        subsistema: "Verificação da Base Rígida",
        atividade: "Inspecionar manualmente se a quantidade de botões de paridade (mamicas) indicada na lateral está compatível com a realidade utilizando o calibre MV-51-9906-043-00",
        resultadoEsperado: "Quantidade de botões na lateral compatível com valor medido.",
        medidas: [{ label: "Quantidade", unidade: "" }],
      },
      {
        numero: 11,
        sistema: "Laterais",
        subsistema: "Verificação do Dimensional das Guias do Triângulo de Freio",
        atividade: "Inspecionar visualmente as chapas da corrediça quanto à sua presença, quanto a trincas, quebras, partes faltantes e sua fixação por solda. Inspecionar manualmente o dimensional da corrediça utilizando o calibre MV-51-9906-012-00.",
        resultadoEsperado: "Chapa de desgaste da corrediça presente, livre de trincas, quebras e partes faltantes. Chapa de desgaste da corrediça fixada com cordão de solda na parte superior. Calibre lado \"passa\" deve ser introduzido por completo e passar em toda a extensão da corrediça, o lado \"não passa\" não deve passar por toda extensão da corrediça e não deve haver contato entre a aba da corrediça e o calibre.",
        medidas: [],
      },
    ],
  },

  "CL-ENG-1033": {
    codigo: "CL-ENG-1033",
    versao: "06.00",
    titulo: "Inspeção da Travessa do Truque Ride Master, Motion Control",
    categoria: "Travessa",
    tipoTruque: "Ride Master, Motion Control",
    modelos: ["RIDE MASTER 6.1/2x9", "MOTION CONTROL 7x12", "MOTION CONTROL 6.1/2x9"],
    dataEmissao: "12/08/2024",
    validadeAte: "12/08/2029",
    procedimentoOrigem: "POP-ENG-1091",
    etapas: [
      {
        numero: 1,
        sistema: "Travessas",
        subsistema: "Ponto Fixo",
        atividade: "Inspecionar visualmente o ponto fixo quanto a empenos e trincas nas soldas. Inspecionar visualmente as buchas quanto à presença, trincas, quebras. Inspecionar com auxílio de um paquímetro ou calibre MV-51-9906-231-00, os desgastes das buchas. Inspecionar com auxílio do goniômetro a angularidade do ponto fixo.",
        resultadoEsperado: "Ponto fixo livre de empenos e trincas nas soldas. Buchas presentes, livre de quebras, trincas, desgastes inferiores à 1/16\" no diâmetro. Ponto fixo com ângulo de 48° + ou – 1°.",
        medidas: [{ label: "Ângulo", unidade: "°" }],
      },
      {
        numero: 2,
        sistema: "Travessas",
        subsistema: "Prato de Pião",
        atividade: "Inspecionar visualmente a borda fundida do prato de pião inferior quanto a trincas, quebras e partes faltantes, válido para travessas dotadas de anel de desgaste ou disco bordeado. Inspecionar visualmente o anel de desgaste do prato de pião inferior quanto a trincas, quebras e partes faltantes.Verificar dimensionalmente o prato de pião, disco bordeado, com o auxílio do cálibre passa ou não passa específico. Medir 4 pontos. MV-51-9906-030 [15\"] e MV-51-9906-151 [16\"].",
        resultadoEsperado: "O calibre não pode entrar no prato de pião pelo lado não passa e deverá passar pelo prato de pião pelo lado passa. A distância máxima entre o prato de pião e o cálibre deve ser de 2mm. O cálibre deverá tocar o fundo do prato de pião ou disco bordeado.",
        medidas: [
          { label: "Medida 1", unidade: "mm" },
          { label: "Medida 2", unidade: "mm" },
          { label: "Medida 3", unidade: "mm" },
          { label: "Medida 4", unidade: "mm" },
        ],
      },
      {
        numero: 3,
        sistema: "Travessas",
        subsistema: "Disco bordeado 15\"",
        atividade: "Realizar manualmente a verificação do desgaste do fundido no sentido transversal e longitudinal com auxílio de trena ou paquímetro. Inspecionar visualmente o disco bordeado quanto a trincas, quebras e partes faltantes. Verificar a folga entre o disco bordeado e o alojamento.",
        resultadoEsperado: "A folga entre a borda do disco bordeado e o fundido deverá ser menor que 4mm. Para travessas dotadas de disco bordeado, o fundido deverá estar com diâmetro minímo de 396 mm e máximo de 397 mm para travessas com prato de pião de 15\".",
        medidas: [{ label: "Medida", unidade: "mm" }],
      },
      {
        numero: 4,
        sistema: "Travessas",
        subsistema: "Disco bordeado 16\"",
        atividade: "Realizar manualmente a verificação do desgaste do fundido no sentido transversal e longitudinal com auxílio de trena ou paquímetro. Inspecionar visualmente o disco bordeado quanto a trincas, quebras e partes faltantes. Verificar a folga entre o disco bordeado e o alojamento.",
        resultadoEsperado: "A folga entre a borda do disco bordeado e o fundido deverá ser menor que 4mm. Para travessas dotadas de disco bordeado, o fundido deverá estar com diâmetro minímo de 421 mm e máximo de 422 mm para travessas com prato de pião de 16\".",
        medidas: [{ label: "Medida", unidade: "mm" }],
      },
      {
        numero: 5,
        sistema: "Travessas",
        subsistema: "Aberturas Internas",
        atividade: "Verificar manualmente a abertura interna da travessa Ride Master aplicando calibre MV-51-9906-069-00.",
        resultadoEsperado: "Abertura interna da travessa, dentro do seu dimensional. Uma lu00e2mina de 5 mm nu00e3o deveru00e1 passar.",
        medidas: [
          { label: "Medida 1", unidade: "mm" },
          { label: "Medida 2", unidade: "mm" },
          { label: "Medida 3", unidade: "mm" },
        ],
      },
      {
        numero: 6,
        sistema: "Travessas",
        subsistema: "Aberturas Externas",
        atividade: "Verificar manualmente a abertura externa da travessa Ride Master aplicando calibre MV-51-9906-068-00.",
        resultadoEsperado: "Abertura externa da travessa, dentro do seu dimensional. Uma lâmina de 5 mm não deverá passar.",
        medidas: [
          { label: "Medida 1", unidade: "mm" },
          { label: "Medida 2", unidade: "mm" },
          { label: "Medida 3", unidade: "mm" },
          { label: "Medida 4", unidade: "mm" },
        ],
      },
      {
        numero: 7,
        sistema: "Travessas",
        subsistema: "Contorno do Alojamento da Cunha",
        atividade: "Verificar manualmente o contorno do alojamento da cunha da travessa Ride Master aplicando calibre MV-51-9906-065-00. Aplicar o calibre na região funcional da bolsa.",
        resultadoEsperado: "Uma lâmina de 3,0 mm (com assentamento em um dos lados) não deverá passar nos pontos X ou Y.",
        medidas: [
          { label: "X ou Y", unidade: "mm" },
          { label: "X ou Y", unidade: "mm" },
          { label: "X ou Y", unidade: "mm" },
          { label: "X ou Y", unidade: "mm" },
        ],
      },
      {
        numero: 8,
        sistema: "Travessas",
        subsistema: "u00c2ngulo do Alojamento da Cunha",
        atividade: "Verificar manualmente o u00e2ngulo do alojamento da cunha aplicando calibre MV-51-9906-064-00. Posicionar o calibre na bolsa da cunha encostando os pontos X e Y.",
        resultadoEsperado: "Uma lu00e2mina de espessura 2,5 mm por 12,5 mm de largura nu00e3o deveru00e1 passar nos pontos W ou Z.",
        medidas: [
          { label: "W ou Z", unidade: "mm" },
          { label: "W ou Z", unidade: "mm" },
          { label: "W ou Z", unidade: "mm" },
          { label: "W ou Z", unidade: "mm" },
        ],
      },
      {
        numero: 9,
        sistema: "Travessas",
        subsistema: "Guias das Cunhas (Lado Direito)",
        atividade: "Verificar manualmente a distu00e2ncia entre guias das cunhas da travessa Ride Master aplicando calibre MV-51-9906-067-00. Medir com paquínetro travessas fabricadas entre 2012 a 2015 conforme desenho MV-51-4567-001-00.",
        resultadoEsperado: "Folga mu00e1xima de 2 mm em cada orelha. Para travessas fabricadas entre 2012 a 2015 a cota da distancia deve esta entre 265,0 a 269,8 mm.",
        medidas: [
          { label: "Medida 1", unidade: "mm" },
          { label: "Medida 2", unidade: "mm" },
          { label: "Medida 3", unidade: "mm" },
          { label: "Medida 4", unidade: "mm" },
        ],
      },
      {
        numero: 10,
        sistema: "Travessas",
        subsistema: "Guias das Cunhas (Lado Esquerdo)",
        atividade: "Verificar manualmente a distu00e2ncia entre guias das cunhas da travessa Ride Master aplicando calibre MV-51-9906-067-00. Medir com paquínetro travessas fabricadas entre 2012 a 2015 conforme desenho MV-51-4567-001-00.",
        resultadoEsperado: "Folga mu00e1xima de 2 mm em cada orelha. Para travessas fabricadas entre 2012 a 2015 a cota da distancia deve esta entre 265,0 a 269,8 mm.",
        medidas: [
          { label: "Medida 1", unidade: "mm" },
          { label: "Medida 2", unidade: "mm" },
          { label: "Medida 3", unidade: "mm" },
          { label: "Medida 4", unidade: "mm" },
        ],
      },
      {
        numero: 11,
        sistema: "Travessas",
        subsistema: "Guias das Cunhas separadas entre travessas 2012 a 2015",
        atividade: "Verificar manualmente a distu00e2ncia entre guias das cunhas da travessa Ride Master utilizando paquímetro. Valor entre 265,0 a 269,8 mm, conforme desenho MV-51-4567-001-00.",
        resultadoEsperado: "Distu00e2ncia da guia da cunha entre 265,0 a 269,8 mm.",
        medidas: [
          { label: "E1", unidade: "mm" },
          { label: "E2", unidade: "mm" },
          { label: "D1", unidade: "mm" },
          { label: "D2", unidade: "mm" },
        ],
      },
      {
        numero: 12,
        sistema: "Travessas",
        subsistema: "Alojamento da Cunha",
        atividade: "Verificar manualmente a distu00e2ncia entre os alojamentos das cunhas da travessa Ride Master aplicando o calibre MV-51-9906-066-00. Apoiar os pontos X na superfu00edcie do alojamento das molas. Etapa 5.3.3 do POP-ENG-1091.",
        resultadoEsperado: "Uma lu00e2mina de 4 mm nu00e3o deveru00e1 passar entre os pontos Y e a superfu00edcie de alojamento das cunhas.",
        medidas: [
          { label: "Y1", unidade: "mm" },
          { label: "Y2", unidade: "mm" },
          { label: "Y3", unidade: "mm" },
          { label: "Y4", unidade: "mm" },
        ],
      },
      {
        numero: 13,
        sistema: "Travessas",
        subsistema: "Fixau00e7u00e3o do Ampara Balu00e7o (Solda)",
        atividade: "Inspecionar visualmente a fixau00e7u00e3o por solda.",
        resultadoEsperado: "Coxim presente, livre de trincas, empenos, quebras ou partes faltantes. Solda coxim executada conforme descrito nos procedimentos.",
        medidas: [],
      },
      {
        numero: 14,
        sistema: "Travessas",
        subsistema: "Fixação do Ampara Balanço (Parafusos)",
        atividade: "Inspecionar visualmente a fixação por solda ou a presença e fixação dos parafusos ou Huckbolt. Coxim presente, livre de trincas, empenos, quebras ou partes faltantes. Parafusos de fixação ou Huckbolt. Os parafusos do coxim deverão ser fixados com torque de 495 a 589,7 Nm.",
        resultadoEsperado: "Coxim presente, livre de trincas, empenos, quebras ou partes faltantes. Parafusos de fixação ou Huckbolt. Os parafusos do coxim deverão ser fixados com torque de 495 a 589,7 Nm.",
        medidas: [{ label: "Torque", unidade: "Nm" }],
      },
      {
        numero: 15,
        sistema: "Travessas",
        subsistema: "Verificação da Folga das Guias anti-rotação MOTION CONTROL",
        atividade: "Verificar manualmente com uso de calibres a distância entre guias das cunhas da travessa Ride Master. Validar entre 4 pontos. Aplicar o calibre MV-51-9906-247-00. A região funcional da bolsa.",
        resultadoEsperado: "Com um dos lados tocando uma lâmina de 2,0 mm de espessura não poderá passar entre o calibre e a guia em toda a região do lado oposto.",
        medidas: [
          { label: "Medida 1", unidade: "mm" },
          { label: "Medida 2", unidade: "mm" },
          { label: "Medida 3", unidade: "mm" },
          { label: "Medida 4", unidade: "mm" },
        ],
      },
      {
        numero: 16,
        sistema: "Travessas",
        subsistema: "Abertura interna MOTION CONTROL",
        atividade: "Verificar manualmente a abertura interna da travesa MOTION CONTROL. Validar entre 4 pontos. Aplicar o calibre MV-51-9906-252-00.",
        resultadoEsperado: "Abertura interna dentro do dimensional sendo que uma lâmina de 4,0 mm não poderá passar em nenhum ponto entre o calibre e região da travessa.",
        medidas: [
          { label: "Medida 1", unidade: "mm" },
          { label: "Medida 2", unidade: "mm" },
          { label: "Medida 3", unidade: "mm" },
          { label: "Medida 4", unidade: "mm" },
        ],
      },
      {
        numero: 17,
        sistema: "Travessas",
        subsistema: "Abertura externa MOTION CONTROL",
        atividade: "Verificar manualmente a abertura externa da travesa MOTION CONTROL. Validar entre 4 pontos. Aplicar o calibre MV-51-9906-251-00.",
        resultadoEsperado: "Abertura externa dentro do dimensional sendo que uma lâmina de 4,0 mm não poderá passar em nenhum ponto entre o calibre e região da travessa.",
        medidas: [
          { label: "Medida 1", unidade: "mm" },
          { label: "Medida 2", unidade: "mm" },
          { label: "Medida 3", unidade: "mm" },
          { label: "Medida 4", unidade: "mm" },
        ],
      },
      {
        numero: 18,
        sistema: "Travessas",
        subsistema: "Verificação da distância entre guias anti-rotação MOTION CONTROL",
        atividade: "Verificar manualmente a distância entre guias anti-rotação MOTION CONTROL. Validar entre 4 pontos. Aplicar o calibre MV-51-9906-250-00. A região funcional da bolsa.",
        resultadoEsperado: "Com um dos lados tocando uma lâmina de 2,0 mm de espessura não poderá passar entre o calibre e a guia em toda a região do lado oposto.",
        medidas: [
          { label: "Medida 1", unidade: "mm" },
          { label: "Medida 2", unidade: "mm" },
          { label: "Medida 3", unidade: "mm" },
          { label: "Medida 4", unidade: "mm" },
        ],
      },
      {
        numero: 19,
        sistema: "Travessas",
        subsistema: "Abertura interna das travessas MOTION CONTROL",
        atividade: "Verificar manualmente a abertura interna da travesa utilizando o calibre MV-51-9906-252-00.",
        resultadoEsperado: "Abertura interna dentro do dimensional sendo que uma lâmina de 4,0 mm não poderá passar em nenhum ponto entre o calibre e região da travessa.",
        medidas: [
          { label: "Medida 1", unidade: "mm" },
          { label: "Medida 2", unidade: "mm" },
          { label: "Medida 3", unidade: "mm" },
          { label: "Medida 4", unidade: "mm" },
        ],
      },
      {
        numero: 20,
        sistema: "Travessas",
        subsistema: "Abertura externa das travessas MOTION CONTROL",
        atividade: "Verificar manualmente a abertura externa da travesa utilizando o calibre MV-51-9906-251-00.",
        resultadoEsperado: "Abertura externa dentro do dimensional sendo que uma lâmina de 4,0 mm não poderá passar em nenhum ponto entre o calibre e região da travessa.",
        medidas: [
          { label: "Medida 1", unidade: "mm" },
          { label: "Medida 2", unidade: "mm" },
          { label: "Medida 3", unidade: "mm" },
          { label: "Medida 4", unidade: "mm" },
        ],
      },
      {
        numero: 21,
        sistema: "Travessas",
        subsistema: "Abertura da guia anti-rotação MOTION CONTROL",
        atividade: "Verificar manualmente a abertura da guia anti-rotação da travesa utilizando o calibre MV-51-9906-256-00.",
        resultadoEsperado: "Abertura da guia anti-rotação dentro do dimensional sendo que uma lâmina de 1,0 mm de espessura não poderá passar entre o calibre e região da travessa em nenhum ponto.",
        medidas: [
          { label: "Medida 1", unidade: "mm" },
          { label: "Medida 2", unidade: "mm" },
        ],
      },
    ],
  },

  "CL-ENG-1034": {
    codigo: "CL-ENG-1034",
    versao: "05.00",
    titulo: "Inspeção da Travessa do Truque Barber",
    categoria: "Travessa",
    tipoTruque: "Barber",
    modelos: ["Barber 6.1/2x12", "Barber 6x11", "Barber 5.1/2x10", "Barber 7x12 S2F", "Barber 6.1/2x9"],
    dataEmissao: "12/08/2024",
    validadeAte: "12/08/2029",
    procedimentoOrigem: "POP-ENG-1088",
    etapas: [
      {
        numero: 1,
        sistema: "Travessa",
        subsistema: "Ponto Fixo",
        atividade: "Inspecionar visualmente o ponto fixo quanto a empenos e trincas nas soldas. Inspecionar visualmente as buchas quanto à presença, trincas, quebras. Inspecionar com auxílio de um Paquímetro ou calibre MV-51-9906-231-00 os desgastes das buchas. Inspecionar com auxílio do goniômetro a angularidade do ponto fixo.",
        resultadoEsperado: "Ponto fixo livre de empenos e trincas nas soldas. Buchas presentes, livre de quebras, trincas, desgastes inferiores à 1/16\" no diâmetro. Ponto fixo com ângulo de 48° + ou – 1°.",
        medidas: [{ label: "Ângulo", unidade: "°" }],
      },
      {
        numero: 2,
        sistema: "Travessa",
        subsistema: "Prato de Pião",
        atividade: "Inspecionar visualmente a borda fundida do prato de pião inferior quanto a trincas, quebras e partes faltantes, válido para travessas dotadas de anel de desgaste ou disco bordeado. Inspecionar visualmente o anel de desgaste do prato de pião inferior quanto a trincas, quebras e partes faltantes.Verificar dimensionalmente o prato de pião, disco bordeado, com o auxílio do cálibre passa ou não passa específico. Medir 4 pontos.",
        resultadoEsperado: "O calibre não pode entrar no prato de pião pelo lado não passa e deverá passar pelo prato de pião pelo lado passa. A distância máxima entre o prato de pião e o cálibre deve ser de 2mm. O cálibre deverá tocar o fundo do prato de pião ou disco bordeado.",
        medidas: [
          { label: "Medida 1", unidade: "mm" },
          { label: "Medida 2", unidade: "mm" },
          { label: "Medida 3", unidade: "mm" },
          { label: "Medida 4", unidade: "mm" },
        ],
      },
      {
        numero: 3,
        sistema: "Travessa",
        subsistema: "Disco bordeado 12\"",
        atividade: "Realizar manualmente a verificação do desgaste do fundido no sentido transversal e longitudinal com auxílio de trena ou paquímetro. Inspecionar visualmente o disco bordeado quanto a trincas, quebras e partes faltantes.Verificar a folga entre o disco bordeado e o alojamento.",
        resultadoEsperado: "A folga entre a borda do disco bordeado e o fundido deverá ser menor que 4mm. Para travessas dotadas de disco bordeado, o fundido deverá estar com diâmetro minímo de 320 mm e máximo de 321 mm para travessas com prato de pião de 12\"",
        medidas: [{ label: "Medida", unidade: "mm" }],
      },
      {
        numero: 4,
        sistema: "Travessa",
        subsistema: "Disco bordeado 14\"",
        atividade: "Realizar manualmente a verificação do desgaste do fundido no sentido transversal e longitudinal com auxílio de trena ou paquímetro. Inspecionar visualmente o disco bordeado quanto a trincas, quebras e partes faltantes.Verificar a folga entre o disco bordeado e o alojamento.",
        resultadoEsperado: "A folga entre a borda do disco bordeado e o fundido deverá ser menor que 4mm. Para travessas dotadas de disco bordeado, o fundido deverá estar com diâmetro minímo de 371 mm e máximo de 372 mm para travessas com prato de pião de 14\"",
        medidas: [{ label: "Medida", unidade: "mm" }],
      },
      {
        numero: 5,
        sistema: "Travessa",
        subsistema: "Disco bordeado 15\"",
        atividade: "Realizar manualmente a verificação do desgaste do fundido no sentido transversal e longitudinal com auxílio de trena ou paquímetro. Inspecionar visualmente o disco bordeado quanto a trincas, quebras e partes faltantes.Verificar a folga entre o disco bordeado e o alojamento.",
        resultadoEsperado: "A folga entre a borda do disco bordeado e o fundido deverá ser menor que 4mm. Para travessas dotadas de disco bordeado, o fundido deverá estar com diâmetro minímo de 396 mm e máximo de 397 mm para travessas com prato de pião de 15\".",
        medidas: [{ label: "Medida", unidade: "mm" }],
      },
      {
        numero: 6,
        sistema: "Travessas",
        subsistema: "Disco bordeado 16\"",
        atividade: "Realizar manualmente a verificação do desgaste do fundido no sentido transversal e longitudinal com auxílio de trena ou paquímetro. Inspecionar visualmente o disco bordeado quanto a trincas, quebras e partes faltantes. Verificar a folga entre o disco bordeado e o alojamento.",
        resultadoEsperado: "A folga entre a borda do disco bordeado e o fundido deverá ser menor que 4mm. Para travessas dotadas de disco bordeado, o fundido deverá estar com diâmetro minímo de 421 mm e máximo de 422 mm para travessas com prato de pião de 16\".",
        medidas: [{ label: "Medida", unidade: "mm" }],
      },
      {
        numero: 7,
        sistema: "Travessas",
        subsistema: "S2A Guias da Bolsa da Cunha",
        atividade: "Verificar manualmente com uso de calibres as dimensões das guias da bolsa da cunha. Calibre MV-51-9906-022 [6\"x11\" e 6.1/2\"x12\"]; MV-51-9906-208 [5.1/2\"x10\"].",
        resultadoEsperado: "Guias da Bolsa da Cunha livre de desgaste e com dimensões em conformidade à aplicação dos calibres específicos. A folga máxima permitida deverá ser de 2mm.",
        medidas: [
          { label: "Medida 1", unidade: "mm" },
          { label: "Medida 2", unidade: "mm" },
          { label: "Medida 3", unidade: "mm" },
          { label: "Medida 4", unidade: "mm" },
        ],
      },
      {
        numero: 8,
        sistema: "Travessas",
        subsistema: "S2A Largura da Bolsa da Cunha",
        atividade: "Verificar manualmente com o uso de calibres a largura das guias da Bolsa da Cunha. Calibre MV-51-9906-207 [5.1/2\"x10\"]; MV-51-9906-011 [6\"x11\" e 6.1/2\"x12\"].",
        resultadoEsperado: "Largura da Bolsa da Cunha livre de desgaste e com dimensões em conformidade à aplicação dos calibres específicos. A folga máxima permitida deverá ser de 2mm.",
        medidas: [
          { label: "Medida 1", unidade: "mm" },
          { label: "Medida 2", unidade: "mm" },
          { label: "Medida 3", unidade: "mm" },
          { label: "Medida 4", unidade: "mm" },
        ],
      },
      {
        numero: 9,
        sistema: "Travessas",
        subsistema: "S2A Rampas da Cunha",
        atividade: "Inspecionar visualmente e com auxílio do calibre específico a planicidade, desgaste da rampa da cunha e alinhamento entre chapas. Calibre MV-51-9906-028 [6\"x11\" e 6.1/2\"x12\"]; MV-51-9906-209 [5.1/2\"x10\"].",
        resultadoEsperado: "Rampa da Cunha livre de desgaste e com dimensões em conformidade à aplicação dos calibres específicos. Com o calibre assentado deverá haver folga de 5 a 10 mm.",
        medidas: [
          { label: "Medida 1", unidade: "mm" },
          { label: "Medida 2", unidade: "mm" },
          { label: "Medida 3", unidade: "mm" },
          { label: "Medida 4", unidade: "mm" },
        ],
      },
      {
        numero: 10,
        sistema: "Travessas",
        subsistema: "S2F Insertos do Alojamento",
        atividade: "Inspecionar visualmente e com auxílio do calibre MV-51-9906-225-00 os insertos quanto à ausência, trincas, quebras e desgastes. Caso tenha sido necesário a troca do inserto, verificar o encaixe do inserto com o alojamento da cunha.",
        resultadoEsperado: "Alojamento da cunha do truque S2F com insertos presentes, livre de trincas, quebras e com dimensional em conformidade com a aplicação do calibre. Centro do calibre não deve tocar no centro",
        medidas: [],
      },
      {
        numero: 11,
        sistema: "Travessas",
        subsistema: "S2F Insertos do Alojamento",
        atividade: "Posicione o inserto na superficie inclinda de forma que fique centralizada, utilizar calibre MV-51-9906-226-00 da superfície inclinada pode ser necessária.",
        resultadoEsperado: "Se a folga entre a superfície inclinada e os insertos for maior do que 1 mm, uma preparação adicional da superfície inclinada pode ser necessária.",
        medidas: [
          { label: "Medida 1", unidade: "mm" },
          { label: "Medida 2", unidade: "mm" },
          { label: "Medida 3", unidade: "mm" },
          { label: "Medida 4", unidade: "mm" },
        ],
      },
      {
        numero: 12,
        sistema: "Travessas",
        subsistema: "S2F Insertos do Alojamento",
        atividade: "Posicione o inserto de forma que fique nivelado utilizando o calibre MV-51-9906-227-00. Reposicione também caso o calibre de nivelamento não esteja com 2 mm da inserção ou bandeja de molas em qualquer ponto.",
        resultadoEsperado: "Correto posicionamento do inserto de forma que fique nivelado e com folga de 2 mm.",
        medidas: [
          { label: "Medida 1", unidade: "mm" },
          { label: "Medida 2", unidade: "mm" },
          { label: "Medida 3", unidade: "mm" },
          { label: "Medida 4", unidade: "mm" },
        ],
      },
      {
        numero: 13,
        sistema: "Travessas",
        subsistema: "S2F Alojamento da cunha",
        atividade: "Inspecionar manualmente com auxílio do calibre o dimensional das chapas instaladas no alojamento da cunha, inserindo o calibre na porção superior do alojamento da cunha. Calibre MV-51-9906-224 [7\"x12\"]; MV-51-9906-241 [6.1/2\"x9\"]",
        resultadoEsperado: "Uma lâmina de 6mm não deve passar. Chapas de desgastes com dimensional em conformidade com a aplicação do calibre.",
        medidas: [
          { label: "Medida 1", unidade: "mm" },
          { label: "Medida 2", unidade: "mm" },
          { label: "Medida 3", unidade: "mm" },
          { label: "Medida 4", unidade: "mm" },
        ],
      },
      {
        numero: 14,
        sistema: "Travessas",
        subsistema: "S2F Alojamento da cunha",
        atividade: "Inspecionar visualmente e com auxílio do calibre o dimensional das guias da lateral (Gibs). Calibre MV-51-9906-223 [7\"x12\"]; MV-51-9906-240 [6.1/2\"x9\"]",
        resultadoEsperado: "Uma lâmina de 1 mm não deve passar. Dimensional das guias da lateral (gibs) em conformidade com a aplicação do calibre.",
        medidas: [
          { label: "Medida 1", unidade: "mm" },
          { label: "Medida 2", unidade: "mm" },
          { label: "Medida 3", unidade: "mm" },
          { label: "Medida 4", unidade: "mm" },
        ],
      },
      {
        numero: 15,
        sistema: "Travessas",
        subsistema: "Fixação do Ampara Balanço (parafuso ou Hulkbolt)",
        atividade: "Inspecionar visualmente o coxim quanto a presença de trincas, empenos e quebras ou partes faltantes. Inspecionar visualmente a presença e fixação dos parafusos ou Huckbolt.",
        resultadoEsperado: "Coxim presentes, livre de trincas, empenos, quebras ou partes faltantes. Parafusos de fixação ou Huckbolt. Os parafusos do coxim deverão ser fixados com torque de 495 a 590 Nm.",
        medidas: [
          { label: "Medida 1", unidade: "mm" },
          { label: "Medida 2", unidade: "mm" },
          { label: "Medida 3", unidade: "mm" },
          { label: "Medida 4", unidade: "mm" },
        ],
      },
      {
        numero: 16,
        sistema: "Travessas",
        subsistema: "Fixação do Ampara Balanço (Solda)",
        atividade: "Inspecionar visualmente e com auxílio do calibre específico a dimensões em conformidade à aplicação dos calibres. Inspecionar visualmente a fixação por solda. Solda sem presença de trincas.",
        resultadoEsperado: "Solda sem presença de trincas",
        medidas: [],
      },
    ],
  },

  "CL-ENG-1035": {
    codigo: "CL-ENG-1035",
    versao: "06.00",
    titulo: "Inspeção da Travessa do Truque Ride Control",
    categoria: "Travessa",
    tipoTruque: "Ride Control",
    modelos: ["Ride Control 5.1/2x10", "Ride control 6.1/2x9", "Ride Control 6x11", "Ride Control 6.1/2x12", "Ride control 6.1/2x9 Us.", "Ride control 7x12 Us."],
    dataEmissao: "12/08/2024",
    validadeAte: "12/08/2029",
    procedimentoOrigem: "POP-ENG-1090",
    etapas: [
      {
        numero: 1,
        sistema: "Travessa",
        subsistema: "Ponto Fixo",
        atividade: "Inspecionar visualmente o ponto fixo quanto a empenos e trincas nas soldas. Inspecionar visualmente as buchas quanto à presença, trincas, quebras. Inspecionar com auxílio de um Paquímetro ou calibre MV-51-9906-231-00 os desgastes das buchas. Inspecionar com auxílio do goniômetro a angularidade do ponto fixo.",
        resultadoEsperado: "Ponto fixo livre de empenos e trincas nas soldas. Buchas presentes, livre de quebras, trincas, desgastes inferiores à 1/16\" no diâmetro. Ponto fixo com ângulo de 48° + ou – 1°.",
        medidas: [{ label: "Ângulo", unidade: "°" }],
      },
      {
        numero: 2,
        sistema: "Travessa",
        subsistema: "Prato de Pião",
        atividade: "Inspecionar visualmente a borda fundida do prato de pião inferior quanto a trincas, quebras e partes faltantes, válido para travessas dotadas de anel de desgaste ou disco bordeado. Inspecionar visualmente o anel de desgaste do prato de pião inferior quanto a trincas, quebras e partes faltantes.Verificar dimensionalmente o prato de pião, disco bordeado, com o auxílio do cálibre passa ou não passa específico. Medir 4 pontos.",
        resultadoEsperado: "O calibre não pode entrar no prato de pião pelo lado não passa e deverá passar pelo prato de pião pelo lado passa. A distância máxima entre o prato de pião e o cálibre deve ser de 2mm. O cálibre deverá tocar o fundo do prato de pião ou disco bordeado.",
        medidas: [
          { label: "Medida 1", unidade: "mm" },
          { label: "Medida 2", unidade: "mm" },
          { label: "Medida 3", unidade: "mm" },
          { label: "Medida 4", unidade: "mm" },
        ],
      },
      {
        numero: 3,
        sistema: "Travessa",
        subsistema: "Disco bordeado 12\"",
        atividade: "Realizar manualmente a verificação do desgaste do fundido no sentido transversal e longitudinal com auxílio de trena ou paquímetro. Inspecionar visualmente o disco bordeado quanto a trincas, quebras e partes faltantes.Verificar a folga entre o disco bordeado e o alojamento.",
        resultadoEsperado: "A folga entre a borda do disco bordeado e o fundido deverá ser menor que 4mm. Para travessas dotadas de disco bordeado, o fundido deverá estar com diâmetro minímo de 320 mm e máximo de 321 para travessas com prato de pião de 12\".",
        medidas: [{ label: "Medida", unidade: "mm" }],
      },
      {
        numero: 4,
        sistema: "Travessa",
        subsistema: "Disco bordeado 14\"",
        atividade: "Realizar manualmente a verificação do desgaste do fundido no sentido transversal e longitudinal com auxílio de trena ou paquímetro. Inspecionar visualmente o disco bordeado quanto a trincas, quebras e partes faltantes. Verificar a folga entre o disco bordeado e o alojamento.",
        resultadoEsperado: "A folga entre a borda do disco bordeado e o fundido deverá ser menor que 4mm. Para travessas dotadas de disco bordeado, o fundido deverá estar com diâmetro minímo de 371 mm e máximo de 372 para travessas com prato de pião de 14\".",
        medidas: [{ label: "Medida", unidade: "mm" }],
      },
      {
        numero: 5,
        sistema: "Travessa",
        subsistema: "Disco bordeado 15\"",
        atividade: "Realizar manualmente a verificação do desgaste do fundido no sentido transversal e longitudinal com auxílio de trena ou paquímetro. Inspecionar visualmente o disco bordeado quanto a trincas, quebras e partes faltantes. Verificar a folga entre o disco bordeado e o alojamento.",
        resultadoEsperado: "A folga entre a borda do disco bordeado e o fundido deverá ser menor que 4mm. Para travessas dotadas de disco bordeado, o fundido deverá estar com diâmetro minímo de 396 mm e máximo de 397 para travessas com prato de pião de 15\".",
        medidas: [{ label: "Medida", unidade: "mm" }],
      },
      {
        numero: 6,
        sistema: "Travessas",
        subsistema: "Disco bordeado 16\"",
        atividade: "Realizar manualmente a verificação do desgaste do fundido no sentido transversal e longitudinal com auxílio de trena ou paquímetro. Inspecionar visualmente o disco bordeado quanto a trincas, quebras e partes faltantes. Verificar a folga entre o disco bordeado e o alojamento.",
        resultadoEsperado: "A folga entre a borda do disco bordeado e o fundido deverá ser menor que 4mm. Para travessas dotadas de disco bordeado, o fundido deverá estar com diâmetro minímo de 421 mm e máximo de 422 mm para travessas com prato de pião de 16\".",
        medidas: [{ label: "Medida", unidade: "mm" }],
      },
      {
        numero: 7,
        sistema: "Travessas",
        subsistema: "Alojamento da cunha",
        atividade: "Verificar manualmente com uso de calibres as dimensões das guias da bolsa da cunha. Calirbre MV-51-9906-128 [5.1/2\"x10\"]; MV-51-9906-021 [6\"x11\"]; MV-51-9906-080 [6.1/2\"x12\" e 6.1/2\"x9\"]; MV-51-9906-196 [6.1/2\"x9\" e 7\"x12\" usinado].",
        resultadoEsperado: "Guias da Bolsa da Cunha livre de desgaste e com dimensões em conformidade à aplicação dos calibres específicos. Uma lâmina de 2,0 mm não deve passar para travessas não usinadas e uma lâmina de 1,0 mm não deve passar para travessas usinadas.",
        medidas: [
          { label: "AE1", unidade: "mm" },
          { label: "AE2", unidade: "mm" },
          { label: "AD1", unidade: "mm" },
          { label: "AD2", unidade: "mm" },
          { label: "BE3", unidade: "mm" },
          { label: "BE4", unidade: "mm" },
          { label: "BD3", unidade: "mm" },
          { label: "BD4", unidade: "mm" },
        ],
      },
      {
        numero: 8,
        sistema: "Travessas",
        subsistema: "Guia anti-rotação",
        atividade: "Verificar manualmente com uso de calibres as dimensões das guias anti-rotação. Calirbre MV-51-9906-130 [5.1/2\"x10\"]; MV-51-9906-004 [6\"x11\"]; MV-51-9906-039 [6.1/2\"x12\" e 6.1/2\"x9\"]; MV-51-9906-185 [6.1/2\"x9\"usinados]; MV51-9906-184 [7\"x12\" usinado].",
        resultadoEsperado: "Para travessas não usinadas uma lâmina de 3,0 mm não deve passar e para travessa usinada uma lâmina de 1,0 mm não deve passar",
        medidas: [
          { label: "LADO DIREITO", unidade: "mm" },
          { label: "LADO ESQUERDO", unidade: "mm" },
        ],
      },
      {
        numero: 9,
        sistema: "Travessas",
        subsistema: "Rampas da Cunha",
        atividade: "Inspecionar visualmente e com auxílio do calibre específico o Ângulo da rampa da cunha.Calibre MV-51-9906-023 [6\"x11\" , 6.1/2\"x12\", 6.1/2\"x9 e o 7\"x12\" e 6.1/2\"x9 usinados]; MV51-9906-129 [5.1/2\"x10\"]",
        resultadoEsperado: "Os pontos X e Y tocando na base da travessa. Se o ponto W tocar, uma lâmina de 2,0 mm não deve passar no ponto Z. Se o ponto Z tocar uma lâmina de 2,0 mm não deve passar no ponto W.",
        medidas: [
          { label: "AE1", unidade: "mm" },
          { label: "AE2", unidade: "mm" },
          { label: "AD1", unidade: "mm" },
          { label: "AD2", unidade: "mm" },
          { label: "BE3", unidade: "mm" },
          { label: "BE4", unidade: "mm" },
          { label: "BD3", unidade: "mm" },
          { label: "BD4", unidade: "mm" },
        ],
      },
      {
        numero: 10,
        sistema: "Travessas",
        subsistema: "Distância entre rampas",
        atividade: "Verificar manualmente com uso de calibres a distância entre rampas do alojomanto da cunha. Calirbre MV-51-9906-127 [5.1/2\"x10\"]; MV-51-9906-025 [6\"x11\"]; MV-51-9906-027 [6.1/2\"x12\" e 6.1/2\"x9\"]; MV-51-9906-186 [7\"x12\" usinado]; MV-51-9906-187 [6.1/2\"x9\" usinado].",
        resultadoEsperado: "Com o calibre tocando simultaneamente na base, uma lâmina de 5,0 mm não deve passar para truques de pedestal largo e uma lâmina de 3,0 mm não deve passar para truques de pedestal estreito.",
        medidas: [
          { label: "LADO D1", unidade: "mm" },
          { label: "LADO D2", unidade: "mm" },
          { label: "LADO E1", unidade: "mm" },
          { label: "LADO E2", unidade: "mm" },
        ],
      },
      {
        numero: 11,
        sistema: "Travessas",
        subsistema: "Planicidade e alinhamento entre chapas da rampa",
        atividade: "Verificar manualmente com o calibre MV51-9906-063-00 a planicidade e o alinhamento entre as chapas da rampa da cunha.",
        resultadoEsperado: "Uma lâmina de 1 mm não deve passar.",
        medidas: [
          { label: "LADO D1", unidade: "mm" },
          { label: "LADO D2", unidade: "mm" },
          { label: "LADO E1", unidade: "mm" },
          { label: "LADO E2", unidade: "mm" },
        ],
      },
      {
        numero: 12,
        sistema: "Travessas",
        subsistema: "Inspecção do coxim do ampara balanço de rolete",
        atividade: "Inspecionar visualmente o coxim quanto a presença de trincas, empenos e quebras ou partes faltantes. Inspecionar visualmente a presença e fixação dos parafusos do ampara balanço STUCKI 688-B atentando para a fixação do coxim com parafusos.",
        resultadoEsperado: "Os parafusos do coxim deverão ser fixados com torque de 500 a 550 Nm.",
        medidas: [{ label: "Torque", unidade: "Nm" }],
      },
      {
        numero: 13,
        sistema: "Travessas",
        subsistema: "Inspecção do coxim do ampara balanço constante",
        atividade: "Inspecionar visualmente quanto a presença de trinca, empenos, quebras ou partes faltantes. Inspecionar visualmente a presença e fixação dos parafusos ou Huckbolts.",
        resultadoEsperado: "Os parafusos do coxim deverão ser fixados com torque de 495 a 590 Nm.",
        medidas: [{ label: "Torque", unidade: "Nm" }],
      },
      {
        numero: 14,
        sistema: "Travessas",
        subsistema: "Inspecção do coxim do ampara balanço constante TCC 45",
        atividade: "Inspecionar visualmente quanto a presença de trinca, empenos, quebras ou partes faltantes. Instalar as chapas de complemento de acordo com o modelo da travessa utilizando solda. Soldar o inserto para travar o ampara balanço.",
        resultadoEsperado: "Ampara balanço instalado com as chapas de complemento ajustadas e soldas conforme modelo da travessa.",
        medidas: [],
      },
      {
        numero: 15,
        sistema: "Travessas",
        subsistema: "Inspecção do coxim do ampara balanço.",
        atividade: "Inspecionar visualmente quanto a presença de trinca, empenos, quebras ou partes faltantes. Inspecionar a solda do coxim.",
        resultadoEsperado: "Soldas livres de trincas, quebras ou partes faltantes.",
        medidas: [],
      },
    ],
  },

  "CL-ENG-1036": {
    codigo: "CL-ENG-1036",
    versao: "04.00",
    titulo: "Inspeção da Travessa do Truque Swing Motion",
    categoria: "Travessa",
    tipoTruque: "Swing Motion",
    modelos: ["Travessa Swing Motion 6.1/2x9", "Travessa Swing Motion 7x12"],
    dataEmissao: "12/08/2024",
    validadeAte: "12/08/2029",
    procedimentoOrigem: "POP-ENG-1092",
    etapas: [
      {
        numero: 1,
        sistema: "Travessa",
        subsistema: "Ponto Fixo",
        atividade: "Inspecionar visualmente o ponto fixo quanto a empenos e trincas nas soldas. Inspecionar visualmente as buchas quanto à presença, trincas, quebras. Inspecionar com auxílio de um Paquímetro ou calibre MV-51-9906-231-00 os desgastes das buchas. Inspecionar com auxílio do goniômetro a angularidade do ponto fixo.",
        resultadoEsperado: "Ponto fixo livre de empenos e trincas nas soldas. Buchas presentes, livre de quebras, trincas, desgastes inferiores à 1/16\" no diâmetro. Ponto fixo com ângulo de 48° + ou – 1°.",
        medidas: [{ label: "Ângulo", unidade: "°" }],
      },
      {
        numero: 2,
        sistema: "Travessa",
        subsistema: "Prato de Pião",
        atividade: "Inspecionar visualmente a borda fundida do prato de pião inferior quanto a trincas, quebras e partes faltantes, válido para travessas dotadas de anel de desgaste ou disco bordeado. Inspecionar visualmente o anel de desgaste do prato de pião inferior quanto a trincas, quebras e partes faltantes.Verificar dimensionalmente o prato de pião, disco bordeado, com o auxílio do cálibre passa ou não passa específico. Medir 4 pontos. MV-51-9906-030 [15\"] e MV-51-9906-151 [16\"].",
        resultadoEsperado: "O calibre não pode entrar no prato de pião pelo lado não passa e deverá passar pelo prato de pião pelo lado passa. A distância máxima entre o prato de pião e o cálibre deve ser de 2mm. O cálibre deverá tocar o fundo do prato de pião ou disco bordeado.",
        medidas: [
          { label: "Medida 1", unidade: "mm" },
          { label: "Medida 2", unidade: "mm" },
          { label: "Medida 3", unidade: "mm" },
          { label: "Medida 4", unidade: "mm" },
        ],
      },
      {
        numero: 3,
        sistema: "Travessa",
        subsistema: "Disco bordeado 15\"",
        atividade: "Realizar manualmente a verificação do desgaste do fundido no sentido transversal e longitudinal com auxílio de trena ou paquímetro. Inspecionar visualmente o disco bordeado quanto a trincas, quebras e partes faltantes.Verificar a folga entre o disco bordeado e o alojamento.",
        resultadoEsperado: "A folga entre a borda do disco bordeado e o fundido deverá ser menor que 4mm. Para travessas dotadas de disco bordeado, o fundido deverá estar com diâmetro minímo de 396 mm e máximo de 397 mm para travessas com prato de pião de 15\".",
        medidas: [{ label: "Medida", unidade: "mm" }],
      },
      {
        numero: 4,
        sistema: "Travessas",
        subsistema: "Disco bordeado 16\"",
        atividade: "Realizar manualmente a verificação do desgaste do fundido no sentido transversal e longitudinal com auxílio de trena ou paquímetro. Inspecionar visualmente o disco bordeado quanto a trincas, quebras e partes faltantes. Verificar a folga entre o disco bordeado e o alojamento.",
        resultadoEsperado: "A folga entre a borda do disco bordeado e o fundido deverá ser menor que 4mm. Para travessas dotadas de disco bordeado, o fundido deverá estar com diâmetro minímo de 421 mm e máximo de 422 mm para travessas com prato de pião de 16\".",
        medidas: [{ label: "Medida", unidade: "mm" }],
      },
      {
        numero: 5,
        sistema: "Travessas",
        subsistema: "Batente da Travessa",
        atividade: "Inspecionar visualmente os batentes quanto a empenos, trincas, quebras, partes faltantes. Caso seja observado desgaste nos batentes, verificar manualmente com uso de trena a distância entre eles.",
        resultadoEsperado: "Batente da travessa livre de empenos, trincas, quebras, partes faltantes e distância entre eles de entre 1380 mm e 1384 mm.",
        medidas: [{ label: "Medida", unidade: "mm" }],
      },
      {
        numero: 6,
        sistema: "Travessas",
        subsistema: "Alojamento da Cunha",
        atividade: "Verificar a planicidade da rampa com utilização de uma escala e um calibre de lâminas.",
        resultadoEsperado: "Folga máxima permitida entre o fundido e régua não poderá permitir a passagem de um espião (lâmina) superior a 0,8 mm.",
        medidas: [
          { label: "E1", unidade: "mm" },
          { label: "E2", unidade: "mm" },
          { label: "D1", unidade: "mm" },
          { label: "D2", unidade: "mm" },
        ],
      },
      {
        numero: 7,
        sistema: "Travessas",
        subsistema: "Alojamento da Cunha",
        atividade: "Verificar manualmente o ângulo e distância entre chapas do alojamento das cunhas utilizando o calibre específico. Calibre MV-51-9906-112 [6.1/2\"x9\"] e MV-51-9906-152 [7\"x12\"].",
        resultadoEsperado: "Folga máxima de 2 mm entre o calibre e a travessa .",
        medidas: [
          { label: "E1", unidade: "mm" },
          { label: "E2", unidade: "mm" },
          { label: "D1", unidade: "mm" },
          { label: "D2", unidade: "mm" },
        ],
      },
      {
        numero: 8,
        sistema: "Travessas",
        subsistema: "Largura da Travessa",
        atividade: "Verificar manualmente a largura da travessa utilizando o calibre específico . Calibre MV-51-9906-114 [6.1/2\" x 9\"] e MV-51-9906-154 [7\" x 12\"].",
        resultadoEsperado: "Passar o calibre de baixo para cima e vice-versa, em toda a superfície recuperada. O calibre deve passar até o limite indicado no instrumento e não deve passar na travessa a partir dessa mesma indicação .",
        medidas: [],
      },
      {
        numero: 9,
        sistema: "Travessas",
        subsistema: "Fixação do Ampara Balanço",
        atividade: "Inspecionar visualmente o coxim quanto à presença, trincas, empenos, quebras ou partes faltantes. Inspecionar visualmente a fixação dos parafusos ou Huckbolt. Torque entre 495 a 589,7 Nm para modelos novos instalados. Porca auto-travante deve transpassar pelo menos 1 fio de rosca, para parafusos instalados ou presentes no coxim",
        resultadoEsperado: "Torque entre 495 a 589,7 Nm para modelos novos instalados. Porca auto-travante deve transpassar pelo menos 1 fio de rosca, para parafusos instalados ou presentes no coxim",
        medidas: [{ label: "Torque", unidade: "Nm" }],
      },
      {
        numero: 10,
        sistema: "Travessas",
        subsistema: "Fixação do Ampara Balanço",
        atividade: "Inspecionar visualmente o coxim quanto à presença, trincas, empenos, quebras ou partes faltantes. Inspecionar visualmente a fixação por solda.",
        resultadoEsperado: "A solda coxim deverrá ser executada conforme descrito nos procedimentos.",
        medidas: [],
      },
    ],
  },
};

export const ALL_CHECKLISTS = Object.values(CHECKLISTS_CONFIG);

export function getChecklistConfig(checklistType: ChecklistType): ChecklistConfig {
  const config = CHECKLISTS_CONFIG[checklistType];
  if (!config) {
    throw new Error(`Checklist type "${checklistType}" not found in configuration`);
  }
  return config;
}

// Adicionar CL-ENG-1066 antes do fechamento
const CL_ENG_1066_CONFIG: ChecklistConfig = {
  codigo: "CL-ENG-1066",
  versao: "00.00",
  titulo: "Inspeção e Recuperação de Triângulo de Freio",
  categoria: "Triângulo",
  tipoTruque: "Triângulo de Freio",
  modelos: ["Convencional", "Stucki", "Direito", "Esquerdo", "Reto (7\"x12\")"],
  dataEmissao: "14/11/2025",
  validadeAte: "14/11/2030",
  procedimentoOrigem: "POP-ENG-1013",
  etapas: [
    {
      numero: 1,
      sistema: "TRIÂNGULO DE FREIO",
      subsistema: "Recuperação do topo do triângulo de freio",
      atividade: "As chapas de desgaste dos topos do triângulo devem ser obrigatoriamente substituídas por novas, retirar com uso de maçarico e lixadeira para limpeza das borras e rebarbas e realizar a fixação de novas chapas utilizando soldagem. Após soldagem, conferir a dimensão com calibre MV-51-9906-013-00. Triângulos STUCKI não possui chapa de desgaste e não é recuperável",
      resultadoEsperado: "Lado \"PASSA\" do calibre deve passar e o lado \"NÃO PASSA\" não deve passar na chapa do topo do triângulo. Para triângulos STUCKI é permitido folga máxima de até 12,7 mm.",
      medidas: [],
    },
    {
      numero: 2,
      sistema: "TRIÂNGULO DE FREIO",
      subsistema: "Inspecionar a contrassapata do triângulo de freio",
      atividade: "Examinar as contra-sapatas na bancada verificando trincas, empenos e quebras. As contra-sapatas que apresentarem desgaste ou deformação devem ser reconstituídas por solda utilizando eletrodo ou arame Mig similar, as demais devem ser subsituidas. Conferir a dimensão com calibre desenho MV-51-9906-014",
      resultadoEsperado: "O lado \"PASSA\" do calibre deve passar livremente. O lado do contorno uma lâmina de 2,0mm não pode passar nas folgas.",
      medidas: [],
    },
    {
      numero: 3,
      sistema: "TRIÂNGULO DE FREIO",
      subsistema: "Bucha do fulcro do triângulo de freio",
      atividade: "Avaliar, utilizando um paquímetro, as buchas do ponto fixo (fulcro) do triângulo se apresentam desgastes, trincas ou partes faltantes, ou poderá ser utilizado o calibre MV-51-9906-231-00.",
      resultadoEsperado: "Permitido desgaste igual ou menor a 1/16\" (1,6 mm). Na utilização do calibre o lado \"PASSA\" deve passar e o lado \"NÃO PASSA\" não pode passar.",
      medidas: [],
    },
    {
      numero: 4,
      sistema: "TRIÂNGULO DE FREIO",
      subsistema: "Inspeção quanto a torções e empenos na bancada de teste - Topo",
      atividade: "Inspecionar o apoio do topo na bancada.",
      resultadoEsperado: "Uma lâmina de 3 mm não deve passar em um em nenhum ponto.",
      medidas: [],
    },
    {
      numero: 5,
      sistema: "TRIÂNGULO DE FREIO",
      subsistema: "Inspeção quanto a torções e empenos na bancada de teste - Contrassapata",
      atividade: "Inspecionar o acentamento da contrassapata bancada de teste.",
      resultadoEsperado: "Uma lâmina de 3 mm não deve passar em um em nenhum ponto.",
      medidas: [],
    },
    {
      numero: 6,
      sistema: "TRIÂNGULO DE FREIO",
      subsistema: "Inspeção quanto a torções e empenos na bancada de teste - Fulcro",
      atividade: "Verificação do posicionamento do fulcro na bancada de teste.",
      resultadoEsperado: "O pino deve passar livremente entre a bucha do fulcro do triângulo e a régua da bancada.",
      medidas: [],
    },
    {
      numero: 7,
      sistema: "TRIÂNGULO DE FREIO",
      subsistema: "Aplicação do suporte de apoio da alavanca viva (Cadeirinha) - Triângulo Esquerdo",
      atividade: "Em todo triângulo esquerdo, deverá ser soldado o suporte de apoio da alavanca viva conforme desenho MV-51-2046-003-00.",
      resultadoEsperado: "Verificar o ângulo da alavanca que deve estar com 48º +ou- 1º em relação ao eixo vertical.",
      medidas: [
        { label: "Ângulo", unidade: "°" },
      ],
    },
  ],
};

// Adicionar ao objeto CHECKLISTS_CONFIG
CHECKLISTS_CONFIG["CL-ENG-1066"] = CL_ENG_1066_CONFIG;

